
USE Quickcart;
--Ranking Function

SELECT *,RANK() OVER(ORDER BY QUANTITYAVAILABLE DESC) AS rank_qty FROM Products

SELECT *,DENSE_RANK() OVER(ORDER BY QUANTITYAVAILABLE DESC) AS dense_rank_qty FROM Products

SELECT *,ROW_NUMBER() OVER(ORDER BY QUANTITYAVAILABLE desc) AS row_num_qty FROM Products


SELECT NTILE5, count(NTILE5) FROM(
SELECT ProductId, ProductName, Price,CategoryId, 
       NTILE(10) OVER (ORDER BY Price Desc) AS NTILE5 FROM Products) A GROUP BY NTILE5

SELECT ProductId, ProductName, Price,CategoryId, 
       RANK() OVER (PARTITION BY CategoryId ORDER BY Price DESC) 
AS Rank FROM Products

--Conversion Function

BEGIN 
     DECLARE @NumOne VARCHAR(2)   
     DECLARE @NumTwo VARCHAR(2)      
     SET @NumOne=20 
     SET @NumTwo=15  
	 SELECT @NumOne + @NumTwo as total_char
	 SELECT CAST(@NumOne AS INT) + CAST(@NumTwo AS INT) AS Total_INT
END  -- VARCHAR TO INT

SELECT CONVERT(FLOAT, '17.85') AS ResultOne, 
       CONVERT(INT, 17.85) AS ResultTwo


--Mathematical Function

SELECT ROUND(49.5,0) AS ResultOne, ROUND(49.49,0) AS ResultTwo, ROUND(27.888,1) as ResultThree

SELECT CEILING(49.1) AS Result

SELECT FLOOR(49.9) AS Result

--String Functions

SELECT SUBSTRING('Microsoft SQL Server',11,10) AS Result

SELECT REVERSE('Microsoft SQL Server') AS Result

SELECT CONCAT('Microsoft',' SQL',' Server') AS Result
SELECT 'Microsoft'+' SQL' as result

SELECT LOWER('Microsoft SQL Server') AS Result

SELECT UPPER('Microsoft SQL Server')AS Result

--Date functions

 SELECT GETDATE() AS 'Current Date and Time'
 SELECT MONTH(GETDATE()) AS 'Month'

SELECT DATEFROMPARTS ( 2016, 12, 31 ) AS Result
SELECT DATETIMEFROMPARTS ( 2016, 12, 31, 23, 59, 59, 0 ) AS Result
SELECT EOMONTH(GETDATE(),2) AS Result

 


SELECT DATEPART(YEAR, GETDATE()) AS YEAR,
       DATEPART(QUARTER, GETDATE()) AS QUARTER,
       DATEPART(MONTH, GETDATE()) AS MONTH,
       DATEPART(DAYOFYEAR, GETDATE()) AS DAYOFYEAR,
       DATEPART(DAY, GETDATE()) AS DAY,
       DATEPART(WEEK, GETDATE()) AS WEEK,
       DATEPART(WEEKDAY, GETDATE()) AS DAYOFWEEK,
       DATEPART(HOUR, GETDATE()) AS HOUR,
       DATEPART(MINUTE, GETDATE()) AS MINUTE,
       DATEPART(SECOND, GETDATE()) AS SECOND,
       DATEPART(MILLISECOND, GETDATE()) AS MILLISECOND,
       DATEPART(MICROSECOND, GETDATE()) AS MICROSECOND,
       DATEPART(NANOSECOND, GETDATE()) AS NANOSECOND

SELECT DATENAME(YEAR, GETDATE()) AS YEAR,
       DATENAME(QUARTER, GETDATE()) AS QUARTER,
       DATENAME(MONTH, GETDATE()) AS MONTH,
       DATENAME(DAYOFYEAR, GETDATE()) AS DAYOFYEAR,
       DATENAME(DAY, GETDATE()) AS DAY,
       DATENAME(WEEK, GETDATE()) AS WEEK,
       DATENAME(WEEKDAY, GETDATE()) AS DAYOFWEEK,
       DATENAME(HOUR, GETDATE()) AS HOUR,
       DATENAME(MINUTE, GETDATE()) AS MINUTE,
       DATENAME(SECOND, GETDATE()) AS SECOND,
       DATENAME(MILLISECOND, GETDATE()) AS MILLISECOND,
       DATENAME(MICROSECOND, GETDATE()) AS MICROSECOND,
       DATENAME(NANOSECOND, GETDATE()) AS NANOSECOND

SELECT CAST(DATEPART(MINUTE,SYSDATETIME()) AS VARCHAR) + CAST(DATEPART(HOUR,GETDATE()) AS VARCHAR)
SELECT CAST(DATEPART(MINUTE,GETDATE()) AS INT) + CAST(DATENAME(HOUR,GETDATE()) AS FLOAT)
SELECT SYSDATETIME(), GETDATE()